const correct = {
  _id: ObjectId("62e10ebba4823f21f10532ad"),
  data: {
    delivery: {
      country: "81",
      zip: "59757",
      city: "Arnsberg",
      street: "Im Ohl",
      houseNumber: "33",
    },
    contactPerson: {
      salutation: "Frau",
      firstName: "Maryna",
      lastName: "Fesenko",
      birthday: "1992-11-15",
    },
    contact: {
      phoneNumber: "017645159752",
      email: "jakobkrocker1@gmail.com",
    },
    payment: {
      paymentType: "sepa",
      iban: "DE32466500050000826081",
    },
    products: [
      {
        rateId: NumberInt(14192),
        consum: "1500",
        branch: "electric",
        type: "private",
        sigDate: "2022-07-27",
        deliveryType: "new",
        deliveryDate: "2022-07-15",
        counterNumber: "500-85823-92",
      },
    ],
  },
  order: [
    {
      orderNo: "310882",
      docInboxRequired: false,
      providerName: "Vattenfall Europe Sales",
      rateName: "Natur24 Direkt Strom",
      orderType: "electric",
      customerType: "private",
    },
  ],
}

const incorrect = {
  _id: ObjectId("62e10ec9a4823f21f10532ae"),
  data: {
    delivery: {
      country: "81",
      zip: "59757",
      city: "Arnsberg",
      street: "Im Ohl",
      houseNumber: "33",
    },
    contactPerson: {
      salutation: "Frau",
      firstName: "Maryna",
      lastName: "Fesenko",
      birthday: "1992-11-15",
    },
    contact: {
      phoneNumber: "017645159752",
      email: "jakobkrocker1@gmail.com",
    },
    payment: {
      paymentType: "sepa",
      iban: "DE32466500050000826081",
    },
    products: [
      {
        rateId: NumberInt(14192),
        consum: "1500",
        branch: "electric",
        type: "private",
        sigDate: "2022-07-27",
        deliveryType: "new",
        deliveryDate: "2022-07-15",
        counterNumber: "500-85823-92",
      },
    ],
  },
  order: {
    error: true,
    serviceName: "OrderService",
    namespace: "aos",
    method: "exportOrder",
    message:
      "Für diese Zählernummer können keine weitere Aufträge entgegen genommen werden.",
    code: NumberInt(400),
    data: {
      delivery: {
        country: "81",
        zip: "59757",
        city: "Arnsberg",
        street: "Im Ohl",
        houseNumber: "33",
      },
      contactPerson: {
        salutation: "Frau",
        firstName: "Maryna",
        lastName: "Fesenko",
        birthday: "1992-11-15",
      },
      contact: {
        phoneNumber: "017645159752",
        email: "jakobkrocker1@gmail.com",
      },
      payment: {
        paymentType: "sepa",
        iban: "DE32466500050000826081",
      },
      products: [
        {
          rateId: NumberInt(14192),
          consum: "1500",
          branch: "electric",
          type: "private",
          sigDate: "2022-07-27",
          deliveryType: "new",
          deliveryDate: "2022-07-15",
          counterNumber: "500-85823-92",
          netzProviderId: NumberInt(4511),
          rate: {
            rateId: NumberInt(14192),
            rateName: "Natur24 Direkt Strom",
            providerName: "Vattenfall Europe Sales",
            basePriceYear: 148.8,
            basePriceMonth: 12.4,
            workPrice: 34.57,
            workPriceNt: NumberInt(0),
            totalPrice: 667.35,
            totalPriceMonth: 55.61,
            rateFileId: NumberInt(18245),
            selfPayment: true,
            requiredEmail: false,
            optEco: true,
            providerChangeFast: true,
            providerDigitalSigned: true,
            partialPayment: NumberInt(11),
            providerId: NumberInt(14),
            cancel: NumberInt(6),
            cancelType: NumberInt(2),
            termBeforeNew: NumberInt(9),
            termBeforeNewType: "months",
            termBeforeNewMaxDate: "27.04.2023",
            termBeforeChange: NumberInt(12),
            termBeforeChangeType: "months",
            termBeforeChangeMaxDate: "27.07.2023",
            termAfterNew: NumberInt(3),
            termAfterNewType: "weeks",
            termAfterNewMaxDate: "06.07.2022",
            optinAdvertisePhone: true,
            optinAdvertiseMobile: true,
            optinAdvertiseEmail: true,
            optinAdvertisePost: false,
            optinAdvertisePersonally: false,
            providerBirthdayMax: NumberInt(0),
            optBonus: NumberInt(0),
            optBonusInstant: NumberInt(0),
            optBonusLoyalty: NumberInt(0),
            optGuarantee: "24",
            optTerm: "24",
          },
        },
      ],
    },
    debug: [
      {
        serviceName: "EgonApiService",
        namespace: "aos",
        method: "checkOrder",
        data: {},
        debug: [
          {
            serviceName: "EgonApiService",
            namespace: "aos",
            method: "checkOrder",
            data: {},
            debug: [],
          },
        ],
      },
    ],
  },
}
